using System;
using System.Collections.Generic;

#nullable disable

namespace apilfs.Models
{
    public partial class VDraftsAll
    {
        public int IdDrafPrincipal { get; set; }
        public int CustomerId { get; set; }
        public string BolSwanleap { get; set; }
        public bool? BookWithAgent { get; set; }
        public decimal WeightDraf { get; set; }
        public string ModeGroup { get; set; }
        public bool? HazmatDraft { get; set; }
        public string SpecialInstructions { get; set; }
        public string Status { get; set; }
        public bool AcceptedTC { get; set; }
        public int? IdDratfSeleQuote { get; set; }
        public decimal? CargoInsurance { get; set; }
        public string RateId { get; set; }
        public int? CarrierId { get; set; }
        public string Scac { get; set; }
        public decimal? GrossCharge { get; set; }
        public decimal? MinInsuredCostQuote { get; set; }
        public decimal? NetCharge { get; set; }
        public decimal? FuelSurcharge { get; set; }
        public decimal? Discount { get; set; }
        public decimal? TotalShipmentCost { get; set; }
        public decimal? NetPricesTotalShipmentCost { get; set; }
        public decimal? NetPricesFuelSurcharge { get; set; }
        public decimal? NetPricesGrossCharge { get; set; }
        public decimal? NetPricesDiscount { get; set; }
        public decimal? NetPricesAccessorialCharges { get; set; }
        public int? TransitDays { get; set; }
        public DateTime? DeliveryDate { get; set; }
        public string ServiceLevelDescription { get; set; }
        public DateTime? ForPickupAfter { get; set; }
        public DateTime? ForPickupBy { get; set; }
        public decimal? AllInRate { get; set; }
        public decimal? FuelRate { get; set; }
        public decimal? LinehaulRate { get; set; }
        public decimal? AccessorialCost { get; set; }
        public decimal? AllInPlusAccessorialRate { get; set; }
        public decimal? StrikeAllInRate { get; set; }
        public decimal? StrikeFuelRate { get; set; }
        public decimal? StrikeLinehaulRate { get; set; }
        public decimal? StrikeAccessorialCost { get; set; }
        public decimal? StrikeAllInPlusAccessorialRate { get; set; }
        public string Rate { get; set; }
        public decimal? DirectRate { get; set; }
        public string DirectRateOperation { get; set; }
        public decimal? DirectRateNetPrice { get; set; }
        public decimal? DirectRateCargoInsurance { get; set; }
        public decimal? DirectRateMinInsuredCost { get; set; }
        public decimal? TransbordRate { get; set; }
        public string TransbordRateOperation { get; set; }
        public decimal? TransbordRateNetPrice { get; set; }
        public decimal? TransbordRateCargoInsurance { get; set; }
        public decimal? TransbordRateMinInsuredCost { get; set; }
        public string SelectedMexicoRate { get; set; }
        public decimal? TotalCost { get; set; }
        public int? IdPickup { get; set; }
        public string LocationName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Country { get; set; }
        public string AddreesType { get; set; }
        public string ContactName { get; set; }
        public string Street { get; set; }
        public string Street2 { get; set; }
        public string Reference { get; set; }
        public string SpecialIntruction { get; set; }
        public string Accesorials { get; set; }
        public TimeSpan? InitialTime { get; set; }
        public TimeSpan? FinalTime { get; set; }
        public DateTime? InitialDate { get; set; }
        public DateTime? FinalDate { get; set; }
        public int? IdDelivery { get; set; }
        public string LocationNameDelivery { get; set; }
        public string EmailDelivery { get; set; }
        public string PhoneDelivery { get; set; }
        public string CountryDelivery { get; set; }
        public string AddreesTypeDelivery { get; set; }
        public string ContactNameDelivery { get; set; }
        public string StreetDelivery { get; set; }
        public string Street2Delivery { get; set; }
        public string ReferenceDelivery { get; set; }
        public string SpecialIntructionDelivery { get; set; }
        public string AccesorialsDelivery { get; set; }
        public TimeSpan? InitialTimeDelivery { get; set; }
        public TimeSpan? FinalTimeDelivery { get; set; }
        public DateTime? InitialDateDelivery { get; set; }
        public DateTime? FinalDateDelivery { get; set; }
        public int? IdAccesorialCharges { get; set; }
        public decimal? AccessorialCharge { get; set; }
        public string AccessorialDescription { get; set; }
        public string AccessorialCode { get; set; }
        public string AccessorialName { get; set; }
        public string AccessorialCode1 { get; set; }
        public decimal? DefaultRate { get; set; }
        public int? IdCommodities { get; set; }
        public decimal? CommodityClass { get; set; }
        public string Unit { get; set; }
        public decimal? Quantity { get; set; }
        public decimal? Length { get; set; }
        public decimal? Width { get; set; }
        public string Description { get; set; }
        public decimal? WeightAccesorials { get; set; }
        public bool? HazmatCommodities { get; set; }
        public string HazmatClass { get; set; }
        public string UnNumber { get; set; }
        public string ParkingGroup { get; set; }
        public decimal? Height { get; set; }
        public int? IdOfficeCustomer { get; set; }
        public string NomberOffice { get; set; }
        public string PhoneOffice { get; set; }
        public string EmailOffice { get; set; }
        public string StreetOffice { get; set; }
        public string CityOffcie { get; set; }
        public string StateOffice { get; set; }
        public string ZipCode { get; set; }
        public string CountryOffice { get; set; }
        public string LocationOffice { get; set; }
        public int? Id { get; set; }
        public int? IdDraft { get; set; }
        public string InsuredCargoOwner { get; set; }
        public string CargoOwnerCountry { get; set; }
        public decimal? TotalCargoValue { get; set; }
        public bool? InsureFreight { get; set; }
        public decimal? CargoInsuran { get; set; }
        public decimal? MinInsuredCost { get; set; }
        public string CommodityType { get; set; }
        public bool? CargoInsuranceActive { get; set; }
    }
}
